# Tables

Tables are a fundamental object type for representing data sets. A table can be viewed in two ways:
* a sequence of named columns that each describe a single aspect of all entries in a data set, or
* a sequence of rows that each contain all information about a single entry in a data set.

In order to use tables, import the `polars` library. In Polars, a table is a DataFrame.

In [2]:
import numpy as np
np.set_printoptions(threshold=50)
path_data = 'data/'

In [3]:
import polars as pl

Empty tables can be created using `pl.DataFrame()`. An empty table is useful because it can be extended to contain new rows and columns.

In [4]:
pl.DataFrame()

shape: (0, 0)
┌┐
╞╡
└┘

The most common way to construct a table is to pass a dictionary of labeled columns to `pl.DataFrame`. Each column of a table is a Series.

You can also add columns later with the `with_columns` method. To add one new column to a table, call `with_columns` with a Series.

Below, we begin each example with an empty table that has no columns.

In [5]:
pl.DataFrame().with_columns(
    pl.Series('Number of petals', [8, 34, 5])
)

shape: (3, 1)
┌──────────────────┐
│ Number of petals │
│ ---              │
│ i64              │
╞══════════════════╡
│ 8                │
│ 34               │
│ 5                │
└──────────────────┘

To add two (or more) new columns, provide a Series for each column. All columns must have the same length, or an error will occur.

In [6]:
pl.DataFrame().with_columns(
    pl.Series('Number of petals', [8, 34, 5]),
    pl.Series('Name', ['lotus', 'sunflower', 'rose'])
)

shape: (3, 2)
┌──────────────────┬───────────┐
│ Number of petals ┆ Name      │
│ ---              ┆ ---       │
│ i64              ┆ str       │
╞══════════════════╪═══════════╡
│ 8                ┆ lotus     │
│ 34               ┆ sunflower │
│ 5                ┆ rose      │
└──────────────────┴───────────┘

We can give this table a name, and then extend the table with another column.

In [7]:
flowers = pl.DataFrame().with_columns(
    pl.Series('Number of petals', [8, 34, 5]),
    pl.Series('Name', ['lotus', 'sunflower', 'rose'])
)

flowers.with_columns(
    pl.Series('Color', ['pink', 'yellow', 'red'])
)

shape: (3, 3)
┌──────────────────┬───────────┬────────┐
│ Number of petals ┆ Name      ┆ Color  │
│ ---              ┆ ---       ┆ ---    │
│ i64              ┆ str       ┆ str    │
╞══════════════════╪═══════════╪════════╡
│ 8                ┆ lotus     ┆ pink   │
│ 34               ┆ sunflower ┆ yellow │
│ 5                ┆ rose      ┆ red    │
└──────────────────┴───────────┴────────┘

The `with_columns` method creates a new table each time it is called, so the original table is not affected. For example, the table `flowers` still has only the two columns that it had when it was created.

In [8]:
flowers

shape: (3, 2)
┌──────────────────┬───────────┐
│ Number of petals ┆ Name      │
│ ---              ┆ ---       │
│ i64              ┆ str       │
╞══════════════════╪═══════════╡
│ 8                ┆ lotus     │
│ 34               ┆ sunflower │
│ 5                ┆ rose      │
└──────────────────┴───────────┘

Creating tables in this way involves a lot of typing. If the data have already been entered somewhere, it is usually possible to use Python to read it into a table, instead of typing it all in cell by cell.

Often, tables are created from files that contain comma-separated values. Such files are called CSV files.

Below, we use `pl.read_csv` to read a CSV file that contains some of the data used by Minard in his graphic about Napoleon's Russian campaign. The data are placed in a table named `minard`.

In [9]:
minard = pl.read_csv(path_data + 'minard.csv')
minard

shape: (8, 5)
┌───────────┬──────────┬─────────────┬───────────┬───────────┐
│ Longitude ┆ Latitude ┆ City        ┆ Direction ┆ Survivors │
│ ---       ┆ ---      ┆ ---         ┆ ---       ┆ ---       │
│ f64       ┆ f64      ┆ str         ┆ str       ┆ i64       │
╞═══════════╪══════════╪═════════════╪═══════════╪═══════════╡
│ 32.0      ┆ 54.8     ┆ Smolensk    ┆ Advance   ┆ 145000    │
│ 33.2      ┆ 54.9     ┆ Dorogobouge ┆ Advance   ┆ 140000    │
│ 34.4      ┆ 55.5     ┆ Chjat       ┆ Advance   ┆ 127100    │
│ 37.6      ┆ 55.8     ┆ Moscou      ┆ Advance   ┆ 100000    │
│ 34.3      ┆ 55.2     ┆ Wixma       ┆ Retreat   ┆ 55000     │
│ 32.0      ┆ 54.6     ┆ Smolensk    ┆ Retreat   ┆ 24000     │
│ 30.4      ┆ 54.4     ┆ Orscha      ┆ Retreat   ┆ 20000     │
│ 26.8      ┆ 54.3     ┆ Moiodexno   ┆ Retreat   ┆ 12000     │
└───────────┴──────────┴─────────────┴───────────┴───────────┘

We will use this small table to demonstrate some useful table methods. We will then use those same methods, and develop other methods, on much larger tables of data.

**The Size of the Table**

The attribute `width` gives the number of columns in the table, and `height` the number of rows.

In [10]:
minard.width

5

In [11]:
minard.height

8

**Column Labels**

The attribute `columns` can be used to list the labels of all the columns. With `minard` we don't gain much by this, but it can be very useful for tables that are so large that not all columns are visible on the screen.

In [12]:
minard.columns

['Longitude', 'Latitude', 'City', 'Direction', 'Survivors']

We can change column labels using the `rename` method. This creates a new table and leaves `minard` unchanged.

In [13]:
minard.rename({"City": "City Name"})

shape: (8, 5)
┌───────────┬──────────┬─────────────┬───────────┬───────────┐
│ Longitude ┆ Latitude ┆ City Name   ┆ Direction ┆ Survivors │
│ ---       ┆ ---      ┆ ---         ┆ ---       ┆ ---       │
│ f64       ┆ f64      ┆ str         ┆ str       ┆ i64       │
╞═══════════╪══════════╪═════════════╪═══════════╪═══════════╡
│ 32.0      ┆ 54.8     ┆ Smolensk    ┆ Advance   ┆ 145000    │
│ 33.2      ┆ 54.9     ┆ Dorogobouge ┆ Advance   ┆ 140000    │
│ 34.4      ┆ 55.5     ┆ Chjat       ┆ Advance   ┆ 127100    │
│ 37.6      ┆ 55.8     ┆ Moscou      ┆ Advance   ┆ 100000    │
│ 34.3      ┆ 55.2     ┆ Wixma       ┆ Retreat   ┆ 55000     │
│ 32.0      ┆ 54.6     ┆ Smolensk    ┆ Retreat   ┆ 24000     │
│ 30.4      ┆ 54.4     ┆ Orscha      ┆ Retreat   ┆ 20000     │
│ 26.8      ┆ 54.3     ┆ Moiodexno   ┆ Retreat   ┆ 12000     │
└───────────┴──────────┴─────────────┴───────────┴───────────┘

However, this method does not change the original table.

In [14]:
minard

shape: (8, 5)
┌───────────┬──────────┬─────────────┬───────────┬───────────┐
│ Longitude ┆ Latitude ┆ City        ┆ Direction ┆ Survivors │
│ ---       ┆ ---      ┆ ---         ┆ ---       ┆ ---       │
│ f64       ┆ f64      ┆ str         ┆ str       ┆ i64       │
╞═══════════╪══════════╪═════════════╪═══════════╪═══════════╡
│ 32.0      ┆ 54.8     ┆ Smolensk    ┆ Advance   ┆ 145000    │
│ 33.2      ┆ 54.9     ┆ Dorogobouge ┆ Advance   ┆ 140000    │
│ 34.4      ┆ 55.5     ┆ Chjat       ┆ Advance   ┆ 127100    │
│ 37.6      ┆ 55.8     ┆ Moscou      ┆ Advance   ┆ 100000    │
│ 34.3      ┆ 55.2     ┆ Wixma       ┆ Retreat   ┆ 55000     │
│ 32.0      ┆ 54.6     ┆ Smolensk    ┆ Retreat   ┆ 24000     │
│ 30.4      ┆ 54.4     ┆ Orscha      ┆ Retreat   ┆ 20000     │
│ 26.8      ┆ 54.3     ┆ Moiodexno   ┆ Retreat   ┆ 12000     │
└───────────┴──────────┴─────────────┴───────────┴───────────┘

A common pattern is to assign the original name `minard` to the new table, so that all future uses of `minard` will refer to the renamed table.

In [15]:
minard = minard.rename({"City": "City Name"})
minard

shape: (8, 5)
┌───────────┬──────────┬─────────────┬───────────┬───────────┐
│ Longitude ┆ Latitude ┆ City Name   ┆ Direction ┆ Survivors │
│ ---       ┆ ---      ┆ ---         ┆ ---       ┆ ---       │
│ f64       ┆ f64      ┆ str         ┆ str       ┆ i64       │
╞═══════════╪══════════╪═════════════╪═══════════╪═══════════╡
│ 32.0      ┆ 54.8     ┆ Smolensk    ┆ Advance   ┆ 145000    │
│ 33.2      ┆ 54.9     ┆ Dorogobouge ┆ Advance   ┆ 140000    │
│ 34.4      ┆ 55.5     ┆ Chjat       ┆ Advance   ┆ 127100    │
│ 37.6      ┆ 55.8     ┆ Moscou      ┆ Advance   ┆ 100000    │
│ 34.3      ┆ 55.2     ┆ Wixma       ┆ Retreat   ┆ 55000     │
│ 32.0      ┆ 54.6     ┆ Smolensk    ┆ Retreat   ┆ 24000     │
│ 30.4      ┆ 54.4     ┆ Orscha      ┆ Retreat   ┆ 20000     │
│ 26.8      ┆ 54.3     ┆ Moiodexno   ┆ Retreat   ┆ 12000     │
└───────────┴──────────┴─────────────┴───────────┴───────────┘

**Accessing the Data in a Column**

We can use a column's label to access the Series of data in the column.

In [19]:
minard["Survivors"]

shape: (8,)
Series: 'Survivors' [i64]
[
	145000
	140000
	127100
	100000
	55000
	24000
	20000
	12000
]

The 5 columns are indexed 0, 1, 2, 3, and 4. The column `Survivors` can also be accessed by using its column index.

In [16]:
minard[:, 4]

shape: (8,)
Series: 'Survivors' [i64]
[
	145000
	140000
	127100
	100000
	55000
	24000
	20000
	12000
]

The 8 items in the Series are indexed 0, 1, 2, and so on, up to 7. The items in the column can be accessed using square brackets, as with any Series.

In [17]:
minard[:, 4][0]

145000

In [18]:
minard[:, 4][5]

24000

**Working with the Data in a Column**

Because columns are Series, we can use Series operations on them to discover new information. For example, we can create a new column that contains the percent of all survivors at each city after Smolensk.

In [19]:
initial = minard["Survivors"][0]
minard = minard.with_columns(
    (minard["Survivors"] / initial).alias("Percent Surviving")
)
minard

shape: (8, 6)
┌───────────┬──────────┬─────────────┬───────────┬───────────┬───────────────────┐
│ Longitude ┆ Latitude ┆ City Name   ┆ Direction ┆ Survivors ┆ Percent Surviving │
│ ---       ┆ ---      ┆ ---         ┆ ---       ┆ ---       ┆ ---               │
│ f64       ┆ f64      ┆ str         ┆ str       ┆ i64       ┆ f64               │
╞═══════════╪══════════╪═════════════╪═══════════╪═══════════╪═══════════════════╡
│ 32.0      ┆ 54.8     ┆ Smolensk    ┆ Advance   ┆ 145000    ┆ 1.0               │
│ 33.2      ┆ 54.9     ┆ Dorogobouge ┆ Advance   ┆ 140000    ┆ 0.965517          │
│ 34.4      ┆ 55.5     ┆ Chjat       ┆ Advance   ┆ 127100    ┆ 0.876552          │
│ 37.6      ┆ 55.8     ┆ Moscou      ┆ Advance   ┆ 100000    ┆ 0.689655          │
│ 34.3      ┆ 55.2     ┆ Wixma       ┆ Retreat   ┆ 55000     ┆ 0.37931           │
│ 32.0      ┆ 54.6     ┆ Smolensk    ┆ Retreat   ┆ 24000     ┆ 0.165517          │
│ 30.4      ┆ 54.4     ┆ Orscha      ┆ Retreat   ┆ 20000     ┆ 0.137931          │
│ 26.8      ┆ 54.3     ┆ Moiodexno   ┆ Retreat   ┆ 12000     ┆ 0.082759          │
└───────────┴──────────┴─────────────┴───────────┴───────────┴───────────────────┘

To make the proportions in the new column appear as percents, multiply by 100.

In [20]:
minard = minard.with_columns(
    (minard["Percent Surviving"] * 100).alias("Percent Surviving")
)
minard

shape: (8, 6)
┌───────────┬──────────┬─────────────┬───────────┬───────────┬───────────────────┐
│ Longitude ┆ Latitude ┆ City Name   ┆ Direction ┆ Survivors ┆ Percent Surviving │
│ ---       ┆ ---      ┆ ---         ┆ ---       ┆ ---       ┆ ---               │
│ f64       ┆ f64      ┆ str         ┆ str       ┆ i64       ┆ f64               │
╞═══════════╪══════════╪═════════════╪═══════════╪═══════════╪═══════════════════╡
│ 32.0      ┆ 54.8     ┆ Smolensk    ┆ Advance   ┆ 145000    ┆ 100.0             │
│ 33.2      ┆ 54.9     ┆ Dorogobouge ┆ Advance   ┆ 140000    ┆ 96.551724         │
│ 34.4      ┆ 55.5     ┆ Chjat       ┆ Advance   ┆ 127100    ┆ 87.655172         │
│ 37.6      ┆ 55.8     ┆ Moscou      ┆ Advance   ┆ 100000    ┆ 68.965517         │
│ 34.3      ┆ 55.2     ┆ Wixma       ┆ Retreat   ┆ 55000     ┆ 37.931034         │
│ 32.0      ┆ 54.6     ┆ Smolensk    ┆ Retreat   ┆ 24000     ┆ 16.551724         │
│ 30.4      ┆ 54.4     ┆ Orscha      ┆ Retreat   ┆ 20000     ┆ 13.793103         │
│ 26.8      ┆ 54.3     ┆ Moiodexno   ┆ Retreat   ┆ 12000     ┆ 8.275862          │
└───────────┴──────────┴─────────────┴───────────┴───────────┴───────────────────┘

**Choosing Sets of Columns**

The method `select` creates a new table that contains only the specified columns.

In [21]:
minard.select('Longitude', 'Latitude')

shape: (8, 2)
┌───────────┬──────────┐
│ Longitude ┆ Latitude │
│ ---       ┆ ---      │
│ f64       ┆ f64      │
╞═══════════╪══════════╡
│ 32.0      ┆ 54.8     │
│ 33.2      ┆ 54.9     │
│ 34.4      ┆ 55.5     │
│ 37.6      ┆ 55.8     │
│ 34.3      ┆ 55.2     │
│ 32.0      ┆ 54.6     │
│ 30.4      ┆ 54.4     │
│ 26.8      ┆ 54.3     │
└───────────┴──────────┘

The same selection can be made using column indices instead of labels.

In [22]:
minard[:, [0, 1]]

shape: (8, 2)
┌───────────┬──────────┐
│ Longitude ┆ Latitude │
│ ---       ┆ ---      │
│ f64       ┆ f64      │
╞═══════════╪══════════╡
│ 32.0      ┆ 54.8     │
│ 33.2      ┆ 54.9     │
│ 34.4      ┆ 55.5     │
│ 37.6      ┆ 55.8     │
│ 34.3      ┆ 55.2     │
│ 32.0      ┆ 54.6     │
│ 30.4      ┆ 54.4     │
│ 26.8      ┆ 54.3     │
└───────────┴──────────┘

The result of using `select` is a new table, even when you select just one column.

In [23]:
minard.select('Survivors')

shape: (8, 1)
┌───────────┐
│ Survivors │
│ ---       │
│ i64       │
╞═══════════╡
│ 145000    │
│ 140000    │
│ 127100    │
│ 100000    │
│ 55000     │
│ 24000     │
│ 20000     │
│ 12000     │
└───────────┘

Notice that the result is a table, unlike the result of selecting a column with square brackets, which is a Series.

In [24]:
minard["Survivors"]

shape: (8,)
Series: 'Survivors' [i64]
[
	145000
	140000
	127100
	100000
	55000
	24000
	20000
	12000
]

Another way to create a new table consisting of a set of columns is to `drop` the columns you don't want.

In [25]:
minard.drop('Longitude', 'Latitude', 'Direction')

shape: (8, 3)
┌─────────────┬───────────┬───────────────────┐
│ City Name   ┆ Survivors ┆ Percent Surviving │
│ ---         ┆ ---       ┆ ---               │
│ str         ┆ i64       ┆ f64               │
╞═════════════╪═══════════╪═══════════════════╡
│ Smolensk    ┆ 145000    ┆ 100.0             │
│ Dorogobouge ┆ 140000    ┆ 96.551724         │
│ Chjat       ┆ 127100    ┆ 87.655172         │
│ Moscou      ┆ 100000    ┆ 68.965517         │
│ Wixma       ┆ 55000     ┆ 37.931034         │
│ Smolensk    ┆ 24000     ┆ 16.551724         │
│ Orscha      ┆ 20000     ┆ 13.793103         │
│ Moiodexno   ┆ 12000     ┆ 8.275862          │
└─────────────┴───────────┴───────────────────┘

Neither `select` nor `drop` change the original table. Instead, they create new smaller tables that share the same data. The fact that the original table is preserved is useful! You can generate multiple different tables that only consider certain columns without worrying that one analysis will affect the other.

In [26]:
minard

shape: (8, 6)
┌───────────┬──────────┬─────────────┬───────────┬───────────┬───────────────────┐
│ Longitude ┆ Latitude ┆ City Name   ┆ Direction ┆ Survivors ┆ Percent Surviving │
│ ---       ┆ ---      ┆ ---         ┆ ---       ┆ ---       ┆ ---               │
│ f64       ┆ f64      ┆ str         ┆ str       ┆ i64       ┆ f64               │
╞═══════════╪══════════╪═════════════╪═══════════╪═══════════╪═══════════════════╡
│ 32.0      ┆ 54.8     ┆ Smolensk    ┆ Advance   ┆ 145000    ┆ 100.0             │
│ 33.2      ┆ 54.9     ┆ Dorogobouge ┆ Advance   ┆ 140000    ┆ 96.551724         │
│ 34.4      ┆ 55.5     ┆ Chjat       ┆ Advance   ┆ 127100    ┆ 87.655172         │
│ 37.6      ┆ 55.8     ┆ Moscou      ┆ Advance   ┆ 100000    ┆ 68.965517         │
│ 34.3      ┆ 55.2     ┆ Wixma       ┆ Retreat   ┆ 55000     ┆ 37.931034         │
│ 32.0      ┆ 54.6     ┆ Smolensk    ┆ Retreat   ┆ 24000     ┆ 16.551724         │
│ 30.4      ┆ 54.4     ┆ Orscha      ┆ Retreat   ┆ 20000     ┆ 13.793103         │
│ 26.8      ┆ 54.3     ┆ Moiodexno   ┆ Retreat   ┆ 12000     ┆ 8.275862          │
└───────────┴──────────┴─────────────┴───────────┴───────────┴───────────────────┘

All of the methods that we have used above can be applied to any table.