# Sorting Rows

"The NBA is the highest paying professional sports league in the world," [reported CNN](http://edition.cnn.com/2015/12/04/sport/gallery/highest-paid-nba-players/) in March 2016. The table `nba_salaries` contains the salaries of all National Basketball Association players in 2015-2016.

Each row represents one player. The columns are:

| **Column Label**   | Description                                         |
|--------------------|-----------------------------------------------------|
| `PLAYER`           | Player's name                                       |
| `POSITION`         | Player's position on team                           |
| `TEAM`             | Team name                                           |
|`'15-'16 SALARY`    | Player's salary in 2015-2016, in millions of dollars|
 
The code for the positions is PG (Point Guard), SG (Shooting Guard), PF (Power Forward), SF (Small Forward), and C (Center). But what follows doesn't involve details about how basketball is played.

The first row shows that Paul Millsap, Power Forward for the Atlanta Hawks, had a salary of almost $\$18.7$ million in 2015-2016.

In [1]:
import polars as pl
import numpy as np
path_data = '../data/'
np.set_printoptions(threshold=50)

In [2]:
# This table can be found online: https://www.statcrunch.com/app/index.php?dataid=1843341
nba_salaries = pl.read_csv(path_data + 'nba_salaries.csv')
nba_salaries

shape: (417, 4)
┌─────────────────┬──────────┬────────────────────┬────────────────┐
│ PLAYER          ┆ POSITION ┆ TEAM               ┆ '15-'16 SALARY │
│ ---             ┆ ---      ┆ ---                ┆ ---            │
│ str             ┆ str      ┆ str                ┆ f64            │
╞═════════════════╪══════════╪════════════════════╪════════════════╡
│ Paul Millsap    ┆ PF       ┆ Atlanta Hawks      ┆ 18.671659      │
│ Al Horford      ┆ C        ┆ Atlanta Hawks      ┆ 12.0           │
│ Tiago Splitter  ┆ C        ┆ Atlanta Hawks      ┆ 9.75625        │
│ Jeff Teague     ┆ PG       ┆ Atlanta Hawks      ┆ 8.0            │
│ Kyle Korver     ┆ SG       ┆ Atlanta Hawks      ┆ 5.746479       │
│ …               ┆ …        ┆ …                  ┆ …              │
│ Gary Neal       ┆ PG       ┆ Washington Wizards ┆ 2.139          │
│ DeJuan Blair    ┆ C        ┆ Washington Wizards ┆ 2.0            │
│ Kelly Oubre Jr. ┆ SF       ┆ Washington Wizards ┆ 1.92024        │
│ Garrett Temple  ┆ SG       ┆ Washington Wizards ┆ 1.100602       │
│ Jarell Eddie    ┆ SG       ┆ Washington Wizards ┆ 0.561716       │
└─────────────────┴──────────┴────────────────────┴────────────────┘

The table contains 417 rows, one for each player. Only a few of them are displayed: polars shows the first five rows and the last five, with a row of `…` standing in for everything in between. The `head` method allows us to specify how many rows to take from the top, with the default (no specification) being the first five rows of the table.

In [3]:
nba_salaries.head(3)

shape: (3, 4)
┌────────────────┬──────────┬───────────────┬────────────────┐
│ PLAYER         ┆ POSITION ┆ TEAM          ┆ '15-'16 SALARY │
│ ---            ┆ ---      ┆ ---           ┆ ---            │
│ str            ┆ str      ┆ str           ┆ f64            │
╞════════════════╪══════════╪═══════════════╪════════════════╡
│ Paul Millsap   ┆ PF       ┆ Atlanta Hawks ┆ 18.671659      │
│ Al Horford     ┆ C        ┆ Atlanta Hawks ┆ 12.0           │
│ Tiago Splitter ┆ C        ┆ Atlanta Hawks ┆ 9.75625        │
└────────────────┴──────────┴───────────────┴────────────────┘

Look at the rows displayed above and you will see that they are in alphabetical order by team name: the table begins with the Atlanta Hawks and ends with the Washington Wizards. It's also possible to list the same rows in alphabetical order by player name using the `sort` method. The argument to `sort` is a column label.

In [4]:
nba_salaries.sort('PLAYER').head(5)

shape: (5, 4)
┌────────────────┬──────────┬────────────────────────┬────────────────┐
│ PLAYER         ┆ POSITION ┆ TEAM                   ┆ '15-'16 SALARY │
│ ---            ┆ ---      ┆ ---                    ┆ ---            │
│ str            ┆ str      ┆ str                    ┆ f64            │
╞════════════════╪══════════╪════════════════════════╪════════════════╡
│ Aaron Brooks   ┆ PG       ┆ Chicago Bulls          ┆ 2.25           │
│ Aaron Gordon   ┆ PF       ┆ Orlando Magic          ┆ 4.17168        │
│ Aaron Harrison ┆ SG       ┆ Charlotte Hornets      ┆ 0.525093       │
│ Adreian Payne  ┆ PF       ┆ Minnesota Timberwolves ┆ 1.93884        │
│ Al Horford     ┆ C        ┆ Atlanta Hawks          ┆ 12.0           │
└────────────────┴──────────┴────────────────────────┴────────────────┘

To examine the players' salaries, it would be much more helpful if the data were ordered by salary.

To do this, we will first simplify the label of the column of salaries (just for convenience), and then sort by the new label `SALARY`. 

This arranges all the rows of the table in *increasing* order of salary, with the lowest salary appearing first. The output is a new table with the same columns as the original but with the rows rearranged.

In [5]:
nba = nba_salaries.rename({"'15-'16 SALARY": 'SALARY'})
nba.sort('SALARY')

shape: (417, 4)
┌────────────────────────┬──────────┬─────────────────────┬───────────┐
│ PLAYER                 ┆ POSITION ┆ TEAM                ┆ SALARY    │
│ ---                    ┆ ---      ┆ ---                 ┆ ---       │
│ str                    ┆ str      ┆ str                 ┆ f64       │
╞════════════════════════╪══════════╪═════════════════════╪═══════════╡
│ Thanasis Antetokounmpo ┆ SF       ┆ New York Knicks     ┆ 0.030888  │
│ Jordan McRae           ┆ SG       ┆ Phoenix Suns        ┆ 0.049709  │
│ Cory Jefferson         ┆ PF       ┆ Phoenix Suns        ┆ 0.049709  │
│ Elliot Williams        ┆ SG       ┆ Memphis Grizzlies   ┆ 0.055722  │
│ Orlando Johnson        ┆ SG       ┆ Phoenix Suns        ┆ 0.055722  │
│ …                      ┆ …        ┆ …                   ┆ …         │
│ Dwight Howard          ┆ C        ┆ Houston Rockets     ┆ 22.359364 │
│ Carmelo Anthony        ┆ SF       ┆ New York Knicks     ┆ 22.875    │
│ LeBron James           ┆ SF       ┆ Cleveland Cavaliers ┆ 22.9705   │
│ Joe Johnson            ┆ SF       ┆ Brooklyn Nets       ┆ 24.894863 │
│ Kobe Bryant            ┆ SF       ┆ Los Angeles Lakers  ┆ 25.0      │
└────────────────────────┴──────────┴─────────────────────┴───────────┘

These figures are somewhat difficult to compare as some of these players changed teams during the season and received salaries from more than one team; only the salary from the last team appears in the table. Point Guard Phil Pressey, for example, moved from Philadelphia to Phoenix during the year, and might be moving yet again to the Golden State Warriors. 

The CNN report is about the other end of the salary scale – the players who are among the highest paid in the world. 

To order the rows of the table in *decreasing* order of salary, we must use `sort` with the option `descending=True`.

In [6]:
nba.sort('SALARY', descending=True)

shape: (417, 4)
┌────────────────────────┬──────────┬─────────────────────┬───────────┐
│ PLAYER                 ┆ POSITION ┆ TEAM                ┆ SALARY    │
│ ---                    ┆ ---      ┆ ---                 ┆ ---       │
│ str                    ┆ str      ┆ str                 ┆ f64       │
╞════════════════════════╪══════════╪═════════════════════╪═══════════╡
│ Kobe Bryant            ┆ SF       ┆ Los Angeles Lakers  ┆ 25.0      │
│ Joe Johnson            ┆ SF       ┆ Brooklyn Nets       ┆ 24.894863 │
│ LeBron James           ┆ SF       ┆ Cleveland Cavaliers ┆ 22.9705   │
│ Carmelo Anthony        ┆ SF       ┆ New York Knicks     ┆ 22.875    │
│ Dwight Howard          ┆ C        ┆ Houston Rockets     ┆ 22.359364 │
│ …                      ┆ …        ┆ …                   ┆ …         │
│ Orlando Johnson        ┆ SG       ┆ Phoenix Suns        ┆ 0.055722  │
│ Phil Pressey           ┆ PG       ┆ Phoenix Suns        ┆ 0.055722  │
│ Jordan McRae           ┆ SG       ┆ Phoenix Suns        ┆ 0.049709  │
│ Cory Jefferson         ┆ PF       ┆ Phoenix Suns        ┆ 0.049709  │
│ Thanasis Antetokounmpo ┆ SF       ┆ New York Knicks     ┆ 0.030888  │
└────────────────────────┴──────────┴─────────────────────┴───────────┘

Kobe Bryant, in his final season with the Lakers, was the highest paid at a salary of $\$25$ million. Notice that the MVP Stephen Curry doesn't appear among the top 10. He is quite a bit further down the list, as we will see later.

## Named Arguments

The `descending=True` portion of this call expression is called a *named argument*. When a function or method is called, each argument has both a position and a name. Both are evident from the help text of a function or method.

In [7]:
help(nba.sort)

Help on method sort in module polars.dataframe.frame:

sort(by: 'IntoExpr | Iterable[IntoExpr]', *more_by: 'IntoExpr', descending: 'bool | Sequence[bool]' = False, nulls_last: 'bool | Sequence[bool]' = False, multithreaded: 'bool' = True, maintain_order: 'bool' = False) -> 'DataFrame' method of polars.dataframe.frame.DataFrame instance
    Sort the dataframe by the given columns.

    Parameters
    ----------
    by
        Column(s) to sort by. Accepts expression input, including selectors. Strings
        are parsed as column names.
    *more_by
        Additional columns to sort by, specified as positional arguments.
    descending
        Sort in descending order. When sorting by multiple columns, can be specified
        per column by passing a sequence of booleans.
    nulls_last
        Place null values last; can specify a single boolean applying to all columns
        or a sequence of booleans for per-column control.
    multithreaded
        Sort using multiple threads.
    maintain_order
        Whether the order should be maintained if elements are equal.

    Examples
    --------
    Pass a single column name to sort by that column.

    >>> df = pl.DataFrame(
    ...     {
    ...         "a": [1, 2, None],
    ...         "b": [6.0, 5.0, 4.0],
    ...         "c": ["a", "c", "b"],
    ...     }
    ... )
    >>> df.sort("a")
    shape: (3, 3)
    ┌──────┬─────┬─────┐
    │ a    ┆ b   ┆ c   │
    │ ---  ┆ --- ┆ --- │
    │ i64  ┆ f64 ┆ str │
    ╞══════╪═════╪═════╡
    │ null ┆ 4.0 ┆ b   │
    │ 1    ┆ 6.0 ┆ a   │
    │ 2    ┆ 5.0 ┆ c   │
    └──────┴─────┴─────┘

    Sorting by expressions is also supported.

    >>> df.sort(pl.col("a") + pl.col("b") * 2, nulls_last=True)
    shape: (3, 3)
    ┌──────┬─────┬─────┐
    │ a    ┆ b   ┆ c   │
    │ ---  ┆ --- ┆ --- │
    │ i64  ┆ f64 ┆ str │
    ╞══════╪═════╪═════╡
    │ 2    ┆ 5.0 ┆ c   │
    │ 1    ┆ 6.0 ┆ a   │
    │ null ┆ 4.0 ┆ b   │
    └──────┴─────┴─────┘

    Sort by multiple columns by passing a list of columns.

    >>> df.sort(["c", "a"], descending=True)
    shape: (3, 3)
    ┌──────┬─────┬─────┐
    │ a    ┆ b   ┆ c   │
    │ ---  ┆ --- ┆ --- │
    │ i64  ┆ f64 ┆ str │
    ╞══════╪═════╪═════╡
    │ 2    ┆ 5.0 ┆ c   │
    │ null ┆ 4.0 ┆ b   │
    │ 1    ┆ 6.0 ┆ a   │
    └──────┴─────┴─────┘

    Or use positional arguments to sort by multiple columns in the same way.

    >>> df.sort("c", "a", descending=[False, True])
    shape: (3, 3)
    ┌──────┬─────┬─────┐
    │ a    ┆ b   ┆ c   │
    │ ---  ┆ --- ┆ --- │
    │ i64  ┆ f64 ┆ str │
    ╞══════╪═════╪═════╡
    │ 1    ┆ 6.0 ┆ a   │
    │ null ┆ 4.0 ┆ b   │
    │ 2    ┆ 5.0 ┆ c   │
    └──────┴─────┴─────┘

At the very top of this `help` text, the *signature* of the `sort` method appears:

    sort(by, *more_by, descending=False, nulls_last=False, multithreaded=True, maintain_order=False)
    
This describes the names and default values of the arguments to `sort`. The first argument, `by`, can be given either by position or by name, so the following two calls do exactly the same thing.

    sort('SALARY', descending=True)
    sort(by='SALARY', descending=True)

The `*more_by` in the signature means you may pass additional columns to sort by, as in `sort('TEAM', 'SALARY')`. Because those extra columns are collected by position, every argument that follows them must be given by name. Writing `sort('SALARY', True)` would make Python treat `True` as another column to sort by, and raise an error.

When an argument is simply `True` or `False`, naming it is a useful convention anyway, so that it's more obvious what the argument value means.